// Supabase client. (Originally generated by Lovable; extended with an env guard.)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Without these env vars, createClient() throws and white-screens the entire app
// (the homepage queries Supabase on mount). Fall back to inert placeholders so the
// UI still renders; live data (reports map/ticker) simply stays empty until a real
// project is configured. Copy .env.example to .env to enable it.
export const hasSupabaseCredentials = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseCredentials && import.meta.env.DEV) {
  console.warn(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY — ' +
    'live reports are disabled. Copy .env.example to .env and fill in your project credentials.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL ?? 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY ?? 'public-anon-placeholder',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
